# Configuration for Local Voice Assistant (PTT Mode)

model_size: "small" # Whisper model size (e.g., tiny, base, small, medium). Smaller = faster, less RAM.
device: "cpu" # Device for STT model ('cpu', 'cuda', 'mps')
compute_type: "int8" # Quantization type ('int8', 'float16', 'float32')
beam_size: 1 # Beam size for Whisper transcription (1 = greedy, faster)
language: "en-US" # Default language for STT (e.g., en-US, de-DE, fr-FR)
sample_rate: 16000 # Audio sample rate (must match STT model requirement)
vad_aggressiveness: 2 # VAD aggressiveness (0-3, higher = less sensitive)
mic_name: "" # Optional: name (or substring) of mic device.
llm_provider: "anthropic" # Added: Specify 'google', 'openai' or 'anthropic'
ptt_hotkey: "option" # Name of the key for PTT (e.g., "option", "cmd", "ctrl", "shift")
min_ptt_duration: 1.2 # Already defined as constant in Orchestrator class
