# Configuration for Local Voice Assistant (PTT Mode)

model_size: "small" # Whisper model size (e.g., tiny, base, small, medium). Smaller = faster, less RAM.
# model_size: "tiny.en" # Example: English-only tiny model
device: "cpu" # Device for STT model ('cpu', 'cuda', 'mps')
compute_type: "int8" # Quantization type ('int8', 'float16', 'float32')
beam_size: 1 # Beam size for Whisper transcription (1 = greedy, faster)
language: "en-US" # Default language (used for formatting, can be changed via voice command)
sample_rate: 16000 # Audio sample rate (must match STT model requirement)
vad_aggressiveness: 2 # VAD aggressiveness (0-3, higher = less sensitive)
mic_name:
  "" # Optional: name (or substring) of mic device.
  # Leave empty for default. On macOS, often 'Built-in Microphone'.
# --- Obsolete / Removed Settings ---
# picovoice_access_key: "..."
# keyword_paths: ["..."]
# wake_sensitivity: 0.3
# mode: "trigger" # Only hotkey mode is supported now
